# Generated by Django 4.0.2 on 2022-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'other')], max_length=3)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=45)),
                ('visitDate', models.DateField()),
            ],
        ),
    ]
